title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Tirth Thakkar
github_username: VINERAJ
github_repo: "CSAblog2.0"
baseurl: "/CSAblog2.0"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/VINERAJ"}
    - { platform: github, user_url: "https://github.com/SortingMiniProject"}
    - { platform: github, user_url: "https://github.com/nighthawkcoders/teacher_portfolio"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
